apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
        - name: mysite
          image: phase1:v1          # local image from Phase-1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
