apiVersion: v1
kind: Service
metadata:
  name: quiz-activity-deployment
spec:
  type: NodePort
  selector:
    app: quiz-activity
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31500